:microprofile-graphql: https://github.com/eclipse/microprofile-graphql/

image:https://github.com/smallrye/smallrye-graphql/workflows/SmallRye%20CI/badge.svg?branch=master[link="https://github.com/smallrye/smallrye-graphql/actions?query=workflow%3A%22SmallRye+CI%22"]
image:https://semaphoreci.com/api/v1/smallrye/smallrye-graphql/branches/master/badge.svg["Semaphore CI", link="https://semaphoreci.com/smallrye/smallrye-graphql"]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-graphql&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=smallrye_smallrye-graphql"]
image:https://img.shields.io/github/license/thorntail/thorntail.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]

= SmallRye GraphQL

SmallRye GraphQL is an implementation of {microprofile-graphql}[Eclipse MicroProfile GraphQL].

== Instructions

Compile and install this project:

[source,bash]
----
mvn clean install
----

=== Project structure

* link:implementation[] - Implementation of the Eclipse MicroProfile GraphQL API.
* link:implementation-servlet[] - Making the implementation available via Servlet
* link:implementation-jaxrs[] - Making the implementation available via JAX-RS (Experimental)
* link:implementation-vertx[] - Making the implementation available via Vert-X (Experimental)
* link:tck[] - Test suite to run the implementation against the {microprofile-graphql}[Eclipse MicroProfile GraphQL] TCK.
* link:runner[] - Manual TCK testing with GraphiQL

=== Links

* http://github.com/smallrye/smallrye-graphql/[Project Homepage]
* {microprofile-graphql}[Eclipse MicroProfile GraphQL]