:microprofile-graphql: https://github.com/eclipse/microprofile-graphql/

image:https://github.com/smallrye/smallrye-graphql/workflows/SmallRye%20Build/badge.svg?branch=master[link=https://github.com/smallrye/smallrye-graphql/actions?query=workflow%3A%22SmallRye+Build%22]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-graphql&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=smallrye_smallrye-graphql"]
image:https://img.shields.io/github/license/thorntail/thorntail.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]

= SmallRye GraphQL

SmallRye GraphQL is an implementation of {microprofile-graphql}[Eclipse MicroProfile GraphQL].

== Instructions

=== Testing against the released v 1.0.1 of MicroProfile GraphQL

[source,bash]
----
mvn clean install
----

=== Testing against the unreleased v 1.1-SNAPSHOT of MicroProfile GraphQL

(You need to build that version of MicroProfile GraphQL locally first to make the snapshot versions available in your repository)

[source,bash]
----
mvn clean install -Dversion.eclipse.microprofile.graphql=1.1-SNAPSHOT
----

=== Project structure

==== Server

* link:schema-model[] - Serializable model that defines the schema.
* link:schema-builder[] - Builder that create the model from Jandex.
* link:api[] - API (pulling in the MicroProfile API) and allowing us to experiment with api feature not yet in the spec. Code from here might move the the spec at some point.
* link:implementation[] - Implementation of the Eclipse MicroProfile GraphQL API.
* link:implementation-cdi[] - Allow lookup of GraphQL Endpoints via CDI
* link:implementation-servlet[] - Making the implementation available via Servlet
* link:tck[] - Test suite to run the implementation against the {microprofile-graphql}[Eclipse MicroProfile GraphQL] TCK.
* link:runner[] - Manual TCK testing with GraphiQL
* link:integration-tests[] - To run some Integration tests
* link:maven-plugin[] - Maven plugin that generates the GraphQL schema from source files.

==== Client

* link:client-api[] - Client API (pulling in the MicroProfile Client API) and allowing us to experiment with api feature not yet in the spec. Code from here might move the the spec at some point.
* link:client-implementation[] - Implementation of the Eclipse MicroProfile GraphQL Client API.
* link:client-tck[] - Test suite to run the client-implementation against the {microprofile-graphql}[Eclipse MicroProfile GraphQL] Client TCK.

=== Using the Maven plugin
To automatically generate the GraphQL schema from your Maven project, add this to your pom.xml:
[source]
----
<plugin>
    <artifactId>smallrye-graphql-maven-plugin</artifactId>
    <groupId>io.smallrye</groupId>
    <executions>
        <execution>
            <goals>
                <goal>generate-schema</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

The schema will appear as `target/generated/schema.graphql`.

=== Links

* http://github.com/smallrye/smallrye-graphql/[Project Homepage]
* {microprofile-graphql}[Eclipse MicroProfile GraphQL]
