:microprofile-graphql: https://github.com/eclipse/microprofile-graphql/
:graphql-over-http: https://github.com/graphql/graphql-over-http

image:https://github.com/smallrye/smallrye-graphql/workflows/SmallRye%20Build/badge.svg?branch=main[link=https://github.com/smallrye/smallrye-graphql/actions?query=workflow%3A%22SmallRye+Build%22]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-graphql&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=smallrye_smallrye-graphql"]
image:https://img.shields.io/github/license/thorntail/thorntail.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://badges.gitter.im/smallrye-graphql/community.svg[link="https://gitter.im/smallrye-graphql/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

= SmallRye GraphQL

SmallRye GraphQL is an implementation of 

- {microprofile-graphql}[Eclipse MicroProfile GraphQL].
- {graphql-over-http}[GraphQL over HTTP].

== Instructions

=== Testing against the released v 1.1.0 of MicroProfile GraphQL

[source,bash]
----
mvn clean install
----

=== Testing against the unreleased v 2.0-SNAPSHOT of MicroProfile GraphQL

(You need to build that version of MicroProfile GraphQL locally first to make the snapshot versions available in your repository)

[source,bash]
----
mvn clean install -Dversion.eclipse.microprofile.graphql=2.0-SNAPSHOT
----

=== Project structure

==== Common

* link:common/schema-model[Schema Model] (Serializable) that defines the schema.
* link:common/schema-builder[Schema Builder] that create the model from Jandex.

==== Server

* link:server/api[API] (pulling in the MicroProfile API) and allowing us to experiment with api feature not yet in the spec. Code from here might move the the spec at some point.
* link:server/implementation[Implementation] of the Eclipse MicroProfile GraphQL API.
* link:server/implementation-cdi[CDI] Module that allows lookup of GraphQL Endpoints via CDI
* link:server/implementation-servlet[Servlet] Making the implementation available via Servlet
* link:server/tck[TCK] Test suite to run the implementation against the {microprofile-graphql}[Eclipse MicroProfile GraphQL] TCK.
* link:server/runner[Runner] Manual TCK testing with GraphiQL
* link:server/integration-tests[IT] To run some Integration tests

==== Client

* link:client/api[Client API] (pulling in the MicroProfile Client API) and allowing us to experiment with api feature not yet in the spec. Code from here might move the the spec at some point.
* link:client/implementation[Client Implementation] of the Eclipse MicroProfile GraphQL Client API.
* link:client/tck[Client TCK] Test suite to run the client-implementation against the {microprofile-graphql}[Eclipse MicroProfile GraphQL] Client TCK.

==== Tools

* link:tools/maven-plugin[Maven plugin] that generates the GraphQL schema from source files.
* link:tools/gradle-plugin[Gradle plugin] that generates the GraphQL schema from source files.

==== UI

* link:ui/graphiql[GraphiQL] UI for your project

==== Documentation

* link:docs[Documentation] SmallRye GraphQL documentation source

Documentation resides in the `docs` directory and is built using the `mkdocs` tool.
See link:https://www.mkdocs.org/user-guide/installation/[Installation guide] on how to install it.
Then, building the documentation locally will be as simple as running `mkdocs build` in the root
of this repository - the output should appear in the `site` directory. To fix a few things, like
making links work correctly, you should serve the site via Jekyll (`jekyll serve` from the `site` directory)
rather than directly open the HTML files in a browser.

GitHub actions take care of building the site on each tag push, and adding it to the `gh-pages` branch.

=== Links

* http://github.com/smallrye/smallrye-graphql/[Project Homepage]
* {microprofile-graphql}[Eclipse MicroProfile GraphQL]
