:microprofile-graphql: https://github.com/eclipse/microprofile-graphql/

image:https://github.com/smallrye/smallrye-graphql/workflows/SmallRye%20Build/badge.svg?branch=master[link=https://github.com/smallrye/smallrye-graphql/actions?query=workflow%3A%22SmallRye+Build%22]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-graphql&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=smallrye_smallrye-graphql"]
image:https://img.shields.io/github/license/thorntail/thorntail.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]

= SmallRye GraphQL

SmallRye GraphQL is an implementation of {microprofile-graphql}[Eclipse MicroProfile GraphQL].

== Instructions

=== Testing against the released v 1.0.1 of MicroProfile GraphQL

[source,bash]
----
mvn clean install
----

=== Testing against the unreleased v 1.1-SNAPSHOT of MicroProfile GraphQL

(You need to build that version of MicroProfile GraphQL locally first to make the snapshot versions available in your repository)

[source,bash]
----
mvn clean install -Dversion.eclipse.microprofile.graphql=1.1-SNAPSHOT
----

=== Project structure

* link:schema-model[] - Serializable model that defines the schema.
* link:schema-builder[] - Builder that create the model from Jandex.
* link:implementation[] - Implementation of the Eclipse MicroProfile GraphQL API.
* link:implementation-servlet[] - Making the implementation available via Servlet
* link:tck[] - Test suite to run the implementation against the {microprofile-graphql}[Eclipse MicroProfile GraphQL] TCK.
* link:runner[] - Manual TCK testing with GraphiQL
* link:integration-tests[] - To run some Integration tests

=== Links

* http://github.com/smallrye/smallrye-graphql/[Project Homepage]
* {microprofile-graphql}[Eclipse MicroProfile GraphQL]
