= SmallRye GraphQL TODOs

This is a list of things we should still look at. Not yet an issue on the issue board, just here a a reminder.

* Implement and test Optional<>
* Check the Content type for the response of the schema request. It's "plain/text" at the moment
* Check if the Jandex index is available when scanning. There might be Jandex indexes in other jars in the lib. See https://docs.wildfly.org/jandex/org/jboss/jandex/CompositeIndex.html
* Add support (if possible) for Generics (apart from collections)
* See if there is a way to merge the formatting annotation mechanism with the JsonB name one, so there is only one way of doing things
** At the moment there are 2 maps, basically see if we can reduce to one.
* What if a collection is not typed (generics) ? Add a test case with just Collection. Do we get object as the parametered type ?
* Add Deprecate support (fieldDefinitionBuilder.deprecate(...))
* Add Directives support (fieldDefinitionBuilder.withDirectives(...))
* Add TCK and impl for @interface that is not on an interface... so class in Java but interface in graphql.
* Double check the Execution service current request scope. Should that maybe be Dependent ?
* See if we can use Jandex in the Exception List (rather than reflection)
* Make the inclusion of the extension in the error a configurable option ?
* Use beanutil or something to create implementation on the fly for interfaces without concrete implementations


