= SmallRye GraphQL Server

== Configuration Options

=== From MicroProfile GraphQL

* `mp.graphql.defaultErrorMessage` - Error message for blacklisted exceptions. Default "Server Error".
* `mp.graphql.exceptionsBlackList` - Exceptions to be blacklisted. Default Runtime Exceptions.
* `mp.graphql.exceptionsWhiteList` - Exceptions to be whitelisted. Default Checked Exceptions.

=== From SmallRye GraphQL

* `smallrye.graphql.printDataFetcherException` - Include the stacktrace of the data fetching exception in the log output. Default false.
* `smallrye.graphql.allowGet` - Allow HTTP GET Methods. Default false.
* `smallrye.graphql.metrics.enabled` - Enable Metrics. Default false.
* `smallrye.graphql.schema.includeScalars` - Include Scalar definitions in the schema. Default true.
* `smallrye.graphql.schema.includeSchemaDefinition` - Include Schema definition. Default false.
* `smallrye.graphql.schema.includeDirectives` - Include directives in the schema. Default false.
* `smallrye.graphql.schema.includeIntrospectionTypes` - Include Introspection types in the schema. Default false.