name: Automated Backporting

on:
  pull_request_target:
    types: [closed]
    branches: [main]

permissions:
  contents: read

jobs:
  backport:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'triage/backport')
    runs-on: ubuntu-latest

    steps:
      - name: Backport to 2.x
        uses: kiegroup/git-backporting@v4.10.0
        with:
          target-branch: 2.x
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ secrets.GITHUB_TOKEN }}
          no-squash: true
          title: "[2.x] ${{ github.event.pull_request.title }}"
